{"content": "A throwable contains a snapshot of the execution stack of its thread at the time it was created. It can also contain a message string that gives more information about the error. Finally, it can contain a cause: another throwable that caused this throwable to get thrown. The cause facility is also known as the chained exception facility, as the cause can, itself, have a cause, and so on, leading to a \"chain\" of exceptions, each caused by another.\n", "stemmed": "A throwabl contain snapshot execut stack thread time creat . It also contain messag string give inform error . final , contain caus : anoth throwabl caus throwabl get thrown . the caus facil also known chain except facil , caus , , caus , , lead `` chain '' except , caus anoth .", "link": "https://en.wikibooks.org/wiki/Java_Programming/Nesting_Exceptions"}