{"content": "By default, when an exception is thrown, the current method is interrupted, the calling method is interrupted too and so on till the main method. A thrown exception can also be caught using a\ntry/catch statement. Below is how a try/catch statement works:\n", "stemmed": "By default , except thrown , current method interrupt , call method interrupt till main method . A thrown except also caught use try/catch statement . below try/catch statement work :", "link": "https://en.wikibooks.org/wiki/Java_Programming/Throwing_and_Catching_Exceptions"}